version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    environment:
      POSTGRES_USER: 'whales'
      POSTGRES_PASSWORD: 'yourpassword'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  cadvisor:
    image: 'google/cadvisor:latest'
    ports:
      - '8080:8080'
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server --requirepass yourpassword
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  website:
    depends_on:
      - 'postgres'
      - 'redis'
      - 'cadvisor'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/whales'
    env_file:
      - '.docker-env'
    logging:
        driver: gelf
        options:
          gelf-address: 'udp://localhost:12201'

  sidekiq:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: sidekiq -C config/sidekiq.yml.erb
    volumes:
      - '.:/whales'
    env_file:
      - '.docker-env'

  cable:
    depends_on:
      - 'redis'
    build: .
    command: puma -p 28080 cable/config.ru
    ports:
      - '28080:28080'
    volumes:
      - '.:/whales'
    env_file:
      - '.docker-env'

  elasticsearch:
    image: elasticsearch:2.0
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    build: logstash/
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    ports:
      - "12201:12201/udp"

  kibana:
    build: kibana/
    depends_on:
      - 'logstash'
      - 'elasticsearch'
    ports:
      - "5601:5601"

volumes:
  redis:
  postgres:
