#!/usr/bin/env bash
set -e

# This allows us to use the same template
# for development, staging and production.
CONFIG_PATH="/etc/nginx/conf.d/default.conf"
STAGING_IP="192.168.1.99"
STAGING_HOSTNAME="stagingserver"
DOMAIN_NAME="productionexample"
DOMAIN_URL="${DOMAIN_NAME}.com"

if [[ $(hostname) != "${STAGING_HOSTNAME}" ]]; then
  sed -i "s/${STAGING_IP}/${DOMAIN_URL}/g" "${CONFIG_PATH}"
  sed -i "s/productionexample/${DOMAIN_NAME}/g" "${CONFIG_PATH}"
fi

# Execute the CMD from the Dockerfile.
exec "$@"
